version: "3.9"

services:
  marketlink-mongo:
    image: mongo:latest
    container_name: marketlink-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - "27017:27017"
    networks:
      - marketlink-net

  marketlink-api:
    build: .
    container_name: marketlink-api
    depends_on:
      - marketlink-mongo
    environment:
      - MONGO_URI=mongodb://admin:123456@marketlink-mongo:27017/admin
    ports:
      - "8080:5000"
    networks:
      - marketlink-net

networks:
  marketlink-net:
    driver: bridge